### ISSUE TITLE
Invalid Syntax: def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):

### ISSUE THREAD

**Issue by svanschalkwyk** [adamerose/pandasgui#15]
Python 3.7.5
Install from github. 

$python demo.py 
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from pandasgui import show
  File "/home/steph/Projects/pandasgui/pandasgui/__init__.py", line 1, in <module>
    from pandasgui.gui import show
  File "/home/steph/Projects/pandasgui/pandasgui/gui.py", line 10, in <module>
    from pandasgui.widgets import PivotDialog, ScatterDialog
  File "/home/steph/Projects/pandasgui/pandasgui/widgets/__init__.py", line 8, in <module>
    from pandasgui.widgets.plotly_viewer import PlotlyViewer
  File "/home/steph/Projects/pandasgui/pandasgui/widgets/plotly_viewer.py", line 5, in <module>
    import plotly
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/plotly/__init__.py", line 30, in <module>
    from plotly import (
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/plotly/graph_objs/__init__.py", line 98268, in <module>
    import ipywidgets
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/core/ultratb.py", line 119, in <module>
    from IPython.utils import path as util_path
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/utils/path.py", line 17, in <module>
    from IPython.utils.process import system
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/IPython/utils/_process_posix.py", line 23, in <module>
    import pexpect
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax

**Comment by svanschalkwyk** [comment]
Solved one issue:
sudo apt-get remove python-pexpect python3-pexpect
pip install --upgrade pexpect

**Comment by svanschalkwyk** [comment]
sudo apt-get remove python-pexpect python3-pexpect
pip install --upgrade pexpect
