### ISSUE TITLE
An error in simplest PandasGUI script

### ISSUE THREAD

**Issue by dmsh1956** [adamerose/PandasGUI#160]
I am trying to run the simplest pandasGUI example.

```
import pandas as pd
from pandasgui import show
df = pd.DataFrame(([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 
                  columns=['a', 'b', 'c'])
show(df)
```
But  I get the following error.

Traceback (most recent call last):  
  File "C:\Users\Дмитрий\\.spyder-py3\temp.py", line 12, in <module>
    show(df)    
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandasgui\gui.py", line 460, in show
    pandas_gui = PandasGui(settings=settings, **kwargs)    
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandasgui\gui.py", line 73, in __init__
    self.init_ui()   
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandasgui\gui.py", line 161, in init_ui
    self.store.settings.settingsChanged.connect(self.apply_settings)   
**RuntimeError: wrapped C/C++ object of type SettingsStore has been deleted**

**Environment**
Windows 10)
Python 3.9.4 64-bit | Qt 5.15.2 | PyQt5 5.15.4
IDE: Spyder 4.2.5  (other attempt - 5.0.5 - get the same mistake)

**Comment by chadkennedyonline** [comment]
Duplicate of #166
