### ISSUE TITLE
KeyError: 'pandasgui/widgets/../images/case-match.png'

### ISSUE THREAD

**Issue by svanschalkwyk** [adamerose/pandasgui#17]
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-steph'
Traceback (most recent call last):
  File "test_pandas_gui.py", line 6, in <module>
    show(example_df)
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pandasgui-0.1.14.1-py3.7.egg/pandasgui/gui.py", line 365, in show
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pandasgui-0.1.14.1-py3.7.egg/pandasgui/gui.py", line 76, in __init__
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pandasgui-0.1.14.1-py3.7.egg/pandasgui/gui.py", line 129, in setupUI
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pandasgui-0.1.14.1-py3.7.egg/pandasgui/widgets/find_toolbar.py", line 49, in __init__
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in resource_filename
    self, resource_name
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1744, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1765, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'pandasgui/widgets/../images/case-match.png'

**Comment by adamerose** [comment]
I was unable to reproduce this, I think it was fixed a while ago. Let me know if not.
