### ISSUE TITLE
PyQtWebEngine fail to install blocking pandasgui

### ISSUE THREAD

**Issue by morzen** [adamerose/PandasGUI#235]
<img width="1049" alt="Screenshot 2023-07-26 at 23 33 56" src="https://github.com/adamerose/PandasGUI/assets/32000608/11f2bf74-bcc4-4e40-a539-8646245c5971">

I am in a venv environment in a Kali (debian) Vm fresh install, (hardware is M1 mac) and the install fails every time same for a classic "pip install PyQtWebEngine" or "pip install PyQtWebEngine".

The odd thing is that outside venv the install work.

on version of the vms worked with this solve https://stackoverflow.com/questions/61254782/importerror-libqt5qmlmodels-so-5-cannot-open-shared-object-file-no-such-file

"sudo apt-get install python3-pyqt5.qtwebengine"

sadly i can't replicate it and i am stuck unable to install and use pandasgui in my venv.

(
     I am also aware that pandasgui has a small difference of usage when using it on non windows OS.
    
    just a little 
    
    import os
    os.environ['APPDATA'] = ""
    
    https://towardsdatascience.com/is-pandas-easy-to-use-try-this-tool-to-make-it-easier-2071eeffe482
)

**Comment by z-x-x136** [comment]
Me too, my computer is Windows 10 python3.9 version

C:\Users\Zeng xiang xi>pip install pandasgui
WARNING: Ignoring invalid distribution -rotobuf (d:\anaconda\anaconda\lib\site-packages)
Collecting pandasgui
  Using cached pandasgui-0.2.14.tar.gz (218 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)


              It is possible a package already installed in your system
              contains an version that is invalid according to PEP 440.
              You can try `pip install --use-pep517` as a workaround for this problem,
              or rely on a new virtual environment.

              If the problem refers to a package that is not installed yet,
              please contact that package's maintainers or distributors.


      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Zeng xiang xi\AppData\Local\Temp\pip-install-9130qpq_\pandasgui_7f792dbb9851449781f854fdaee56816\setup.py", line 6, in <module>
          setup(
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\setuptools\installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 815, in resolve
          dist = self._resolve_dist(
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 844, in _resolve_dist
          env = Environment(self.entries)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 1044, in __init__
          self.scan(search_path)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 1077, in scan
          self.add(dist)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 1096, in add
          dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 2640, in hashcmp
          self.parsed_version,
        File "C:\Users\Zeng xiang xi\AppData\Roaming\Python\Python39\site-packages\pkg_resources\__init__.py", line 2694, in parsed_version
          raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '4.0.0-unsupported' (package: pyodbc)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
