### ISSUE TITLE
0.2.14 (the latest version on PyPi) cannot be imported without the APPDATA environment variable

### ISSUE THREAD

**Issue by adamtuft** [adamerose/pandasgui#255]
**Describe the bug**  

On linux:

```
pip install pandasgui
python -c "import pandasgui"
```

Output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adam/.venv/pandasgui/lib/python3.11/site-packages/pandasgui/__init__.py", line 15, in <module>
    from pandasgui.gui import show
  File "/home/adam/.venv/pandasgui/lib/python3.11/site-packages/pandasgui/gui.py", line 13, in <module>
    from pandasgui.constants import PANDASGUI_ICON_PATH
  File "/home/adam/.venv/pandasgui/lib/python3.11/site-packages/pandasgui/constants.py", line 15, in <module>
    SHORTCUT_PATH = os.path.join(os.getenv('APPDATA'), 'Microsoft/Windows/Start Menu/Programs/PandasGUI.lnk', )
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This works, however:

```
APPDATA="" python -c "import pandasgui"
```

The `APPDATA` environment variable is not one that is commonly set by default on Linux, which makes it awkward to import this package unless you know that it expects the variable to exist in the environment.

**Environment**
OS: `6.1.85-1-MANJARO GNU/Linux`
Python: 3.11.8

**Package versions**  

```
ipython==8.24.0
pandasgui==0.2.14
plotly==5.22.0
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
```

**Comment by ger08061959** [comment]
The following code works (better):

import os
env = os.getenv('APPDATA')
if env is None:
    os.environ["APPDATA"] = "."

instead of APPDATA="" python -c "import pandasgui" which only did run once.
