### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by rihabbh** [adamerose/pandasgui#43]
Hello,

I'm using Jupyter notebook with Windows 10 and the filters are not working.
When I add a filter I have this error : 

```PandasGUI ERROR — pandasgui.store — False
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandasgui\store.py", line 199, in apply_filters
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py", line 3343, in query
    result = self.loc[res]
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py", line 1110, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py", line 1059, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py", line 3488, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexes\range.py", line 358, in get_loc
    raise KeyError(key)
KeyError: False
```
And the checkbox doesn't appear in the UI : 

![Capture d’écran (177)](https://user-images.githubusercontent.com/23280113/96699186-4642d180-138e-11eb-8651-a9dfafc2b31c.png)

There is also a small issue where the icons don't appear in the "Grapher" section : 
![Capture d’écran (178)](https://user-images.githubusercontent.com/23280113/96700887-3e842c80-1390-11eb-95f8-b960c6e1fbdd.png)

**Comment by adamerose** [comment]
I think your syntax is wrong for the filter, you need to use backticks to refer to column names not single quotes. Read more here:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html

```
from pandasgui.datasets import pokemon

# Correct
pokemon.query("`Type 1` == 'Grass'")

# Incorrect
pokemon.query("'Type 1' == 'Grass'")
```

However I should probably print a more user-friendly warning when a filter is invalid, I'll change that. The checkbox is missing because the filter is invalid, and there should be a warning icon but it's missing just like the Grapher icons.. I'll look into that, I probably have a mistake in my setup.py.

**Comment by rihabbh** [comment]
Ok, The filters are working now, I had to uninstall and reinstall pandasgui  but the icons are now showing.

Thank you.
